### PR TITLE
Add 3.13 to CI

### PR DESCRIPTION
**Pull request by hynek**
We'll need a CFFI release first, though.

ref https://github.com/hynek/argon2-cffi-bindings/pull/57

### CODE REVIEW

**Comment by hynek** [comment]
I’m not sure how that’s possible, since cffi still hasn’t released a version that’s installable on 3.13?!

**Comment by fschulze** [comment]
The devpi-server tests are picking up the 1.17.0rc1 release, so you actually might want to wait further

**Comment by hynek** [comment]
The good news is that it seems to work locally, at least.

**Comment by fschulze** [comment]
The release strategy for CFFI has been explained https://github.com/python-cffi/cffi/issues/71#issuecomment-2059540837 and https://github.com/python-cffi/cffi/issues/71#issuecomment-2128250550. To summarize: No releases during Python alpha phase, pre-release for beta so people can start testing and final release for release candidates (expected July 30th for 3.13).

**Pull request merged**
