### PR TITLE
build abi3 wheels for windows as well

### PR DESCRIPTION
**Pull request by asottile**
relates to #66

this doesn't solve the build-and-upload problem, but it will allow us to build future-proof distributions on windows (as we're already doing for linux / macos)

### CODE REVIEW

**Comment by SmartManoj** [comment]
https://t.me/Python4Channel/157

**Comment by asottile** [comment]
@SmartManoj I'm not sure why you keep posting off-site links to wheels that (arguably) we can't trust to upload

the wheel you've produced is also incorrect, it should be built using cpython3.5

**Comment by SmartManoj** [comment]
Can't upload files here

**Comment by SmartManoj** [comment]
Why it should be built using 3.5?
https://discuss.python.org/t/python-download-stats-for-march-2019/1424

**Comment by asottile** [comment]
the whole point of abi3 is you produce a wheel for your oldest platform and it works on any newer version

**Comment by asottile** [comment]
(please don't bother building a wheel and uploading it, I'm going to automate the whole thing with CI tooling)

**Comment by hynek** [comment]
Wow, finally some good news! Is that documented somewhere?

(Don’t bother automating the upload tho, I have local automation for that will take care of it.)

**Comment by asottile** [comment]
I'm getting close to having the builds happen in github actions, stay tuned! (just need to fix python 2 on windows apparently)

**Comment by hynek** [comment]
I can’t put into words how grateful I am! I hope you’re at least getting good steaming content out of it. 😅

**Comment by asottile** [comment]
by the way, have you seen https://pre-commit.ci yet?  if you want to try out the alpha it's live at https://results.pre-commit.ci

**Comment by SmartManoj** [comment]
uploaded since you are on a vacation and for https://stackoverflow.com/q/64236463/5033247

**Pull request merged**
