### PR TITLE
change wheeling to workflow_dispatch job

### PR DESCRIPTION
**Pull request by asottile**
I don't really have a way to test this, but in theory this should work?

### CODE REVIEW

**Comment by asottile** [comment]
https://twitter.com/artyintheuk/status/1034637711410388992

seems to kinda work: https://github.com/asottile/argon2-cffi/actions/runs/339985780

(I had to merge to master in my fork and toggle actions there)

**Comment by hynek** [comment]
> https://twitter.com/artyintheuk/status/1034637711410388992

Aw man I command you to go to bed. 🙈

You've got two builders failing btw 😬

**Comment by asottile** [comment]
> 
> 
> > https://twitter.com/artyintheuk/status/1034637711410388992
> 
> Aw man I command you to go to bed. 🙈
> 
> You've got two builders failing btw 😬

fixed them I think, I'm more and more baffled by pep517/518 it seems, I thought the whole point was so I _didn't_ have to make sure wheel was installed

https://github.com/asottile/argon2-cffi/runs/1337885645?check_suite_focus=true

**Comment by hynek** [comment]
OK the macOS wheel looks good, thanks!

**Comment by hynek** [comment]
Correct me if I'm wrong, but the quickest way for me to get heat off my neck would be to manually add 3.9 for the two windowses too the build script, upload it to PyPI and remove it again? 🤔

**Comment by asottile** [comment]
yep!

**Comment by asottile** [comment]
unrelated: DST is hard and we're time travelers

image

**Comment by hynek** [comment]
> we're time travelers

I'm OK with that!

---

Thanks again and [listen to Samuel now](https://www.youtube.com/watch?v=Udj-o2m39NA)!

**Pull request merged**
