### PR TITLE
Add pypy wheels for non-linux platforms

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by hynek** [comment]
This is like a super dumb question, but…is there a way to test this without merging it!?

**Comment by asottile** [comment]
I... don't think so :S

**Comment by hynek** [comment]
why is pre-commit.ci failing? 😇

**Comment by asottile** [comment]
that's weird.... the status message thinks that there was an additional commit after your push -- let me see if I can figure out why

**Comment by asottile** [comment]
huh, I guess there's a race on github's side -- looking at the logs it set a webhook with sha: f2ab0, then when the run fired it had sha 308b as HEAD and so it cancelled it due to mismatch -- I'm going to disable that short circuit for now

pre-commit.ci run

^ that'll trigger a rerun

**Comment by hynek** [comment]
I have uploaded the wheels to PyPI. Thank you so much Anthony, you are a true community treasure!

**Pull request merged**
